spring.application.name=ocean-view-backend
# MongoDB (use Atlas or local)
spring.data.mongodb.uri=mongodb+srv://mbaasatheef_db_user:iBvvecU3q0BEReXL@resort.tpvzfik.mongodb.net/?appName=resort
spring.data.mongodb.database=room_reservation

# better to see detailed errors during development
server.error.include-message=always
server.error.include-binding-errors=always

# JWT secret (change this in production! minimum 32 characters)
jwt.secret=your-very-long-and-secure-secret-key-ChangeThis1234567890abcdef
jwt.expiration=86400000  

imgbb.api.key=21b1eae1d5ec2c530e85522961637752
imgbb.api.url=https://api.imgbb.com/1/upload
# optional - show SQL-like queries for MongoDB
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG